//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LR4._2_OOP.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        public string textBox1 { get; internal set; }
        public string textBox2 { get; internal set; }
        public string textBox3 { get; internal set; }
        public decimal numericUpDown1 { get; internal set; }
        public int trackBar1 { get; internal set; }
        public int trackBar2 { get; internal set; }
        public decimal numericUpDown2 { get; internal set; }
        public int trackBar3 { get; internal set; }
        public decimal numericUpDown3 { get; internal set; }
    }
}
